### ISSUE TITLE
Unexpected error occurs when creating an entity generated from Oracle database

### ISSUE THREAD

**Issue by lovtsovaik** [Haulmont/jmix-data#56] opened 2021-03-15 08:50 UTC
bomVersion = '1.0.0-SNAPSHOT'

see also the similar problem for MSSQL in https://github.com/Haulmont/jmix-data/issues/54

1. Connect to Oracle server using a third-party program and execute sql script [Sample-Oracle.sql.txt](https://github.com/Haulmont/jmix-data/files/6139907/Sample-Oracle.sql.txt)
2. Create data store and connect it to this database
3. Click Generate model, refresh list
4. Select All tables -> Finish
5. Add missed attributes to screens if needed
6. Run the app
7. Open Individual browser
8. Create item

AR: Unexpected error occurs when trying to save
> OracleDatabaseException: ORA-00001: нарушено ограничение уникальности (IRA_TEST.SYS_C003581863)
Error : 1, Position : 0, Sql = INSERT INTO INDIVIDUAL ("CUST_ID", "BIRTH_DATE", "FIRST_NAME", "LAST_NAME") VALUES (:1 , :2 , :3 , :4 ), OriginalSql = INSERT INTO INDIVIDUAL ("CUST_ID", "BIRTH_DATE", "FIRST_NAME", "LAST_NAME") VALUES (?, ?, ?, ?), Error Msg = ORA-00001: нарушено ограничение уникальности (IRA_TEST.SYS_C003581863)

The id defined as
```
    @JmixGeneratedValue
    @Column(name = "\"CUST_ID\"", nullable = false)
    @Id
    private Integer id;
```

ER: correct saving

**Comment by dtaimanov** [comment] 2021-04-06 09:06
Duplicate of #54

**Closed** 2021-04-06 09:06 UTC
Labels: state: duplicate, type: bug
