### ISSUE TITLE
Error creating UUID from database value exception while login to the application

### ISSUE THREAD

**Issue by Flaurite** [Haulmont/jmix-data#44] opened 2021-02-11 09:01 UTC
### Description
- database: mysql-5 (probably the same with mariaDb)
- demo project: [dbmysql.zip](https://github.com/Haulmont/jmix-data/files/5963845/dbmysql.zip)

### Steps to reproduce
1. Download demo project;
2. Launch the app and try to login

```
Caused by: org.springframework.security.authentication.InternalAuthenticationServiceException: java.lang.RuntimeException: Error creating UUID from database value '60885987-1b61-4247-94c7-dff348347f93'
	at org.springframework.security.authentication.dao.DaoAuthenticationProvider.retrieveUser(DaoAuthenticationProvider.java:108) ~[spring-security-core-5.4.2.jar:5.4.2]
	at org.springframework.security.authentication.dao.AbstractUserDetailsAuthenticationProvider.authenticate(AbstractUserDetailsAuthenticationProvider.java:133) ~[spring-security-core-5.4.2.jar:5.4.2]
	at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:182) ~[spring-security-core-5.4.2.jar:5.4.2]
	at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:201) ~[spring-security-core-5.4.2.jar:5.4.2]
	at org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter$AuthenticationManagerDelegator.authenticate(WebSecurityConfigurerAdapter.java:510) ~[spring-security-config-5.4.2.jar:5.4.2]
	at io.jmix.securityui.authentication.LoginScreenAuthenticationSupport.authenticate(LoginScreenAuthenticationSupport.java:114) ~[jmix-security-ui-0.3.0-SNAPSHOT.jar:na]
	at com.company.dbmysql.screen.login.LoginScreen.login(LoginScreen.java:85) ~[main/:na]
	at com.company.dbmysql.screen.login.LoginScreen.onSubmitActionPerformed(LoginScreen.java:70) ~[main/:na]
	at io.jmix.core.common.event.EventHub.publish(EventHub.java:170) ~[jmix-core-0.3.0-SNAPSHOT.jar:na]
	at io.jmix.ui.action.BaseAction.actionPerform(BaseAction.java:220) ~[jmix-ui-0.3.0-SNAPSHOT.jar:na]
	at io.jmix.ui.component.impl.ButtonImpl.buttonClicked(ButtonImpl.java:75) ~[jmix-ui-0.3.0-SNAPSHOT.jar:na]
	at io.jmix.ui.widget.JmixButton.fireClick(JmixButton.java:77) ~[jmix-ui-0.3.0-SNAPSHOT.jar:na]
	at com.vaadin.ui.Button$1.click(Button.java:57) ~[vaadin-server-8.9.2-6-jmix.jar:8.9.2-6-jmix]
	... 88 common frames omitted
Caused by: javax.persistence.PersistenceException: java.lang.RuntimeException: Error creating UUID from database value '60885987-1b61-4247-94c7-dff348347f93'
	at org.eclipse.persistence.internal.jpa.QueryImpl.getResultList(QueryImpl.java:493) ~[org.eclipse.persistence.jpa-2.7.7-2-jmix.jar:na]
	at io.jmix.eclipselink.impl.JmixEclipseLinkQuery.getResultFromCache(JmixEclipseLinkQuery.java:767) ~[jmix-eclipselink-0.3.0-SNAPSHOT.jar:na]
	at io.jmix.eclipselink.impl.JmixEclipseLinkQuery.getResultList(JmixEclipseLinkQuery.java:131) ~[jmix-eclipselink-0.3.0-SNAPSHOT.jar:na]
	at io.jmix.eclipselink.impl.JpaDataStore.executeQuery(JpaDataStore.java:466) ~[jmix-eclipselink-0.3.0-SNAPSHOT.jar:na]
	at io.jmix.eclipselink.impl.JpaDataStore.loadAll(JpaDataStore.java:160) ~[jmix-eclipselink-0.3.0-SNAPSHOT.jar:na]
	at io.jmix.core.datastore.AbstractDataStore.loadList(AbstractDataStore.java:127) ~[jmix-core-0.3.0-SNAPSHOT.jar:na]
	at io.jmix.core.impl.DataManagerImpl.loadList(DataManagerImpl.java:91) ~[jmix-core-0.3.0-SNAPSHOT.jar:na]
	at io.jmix.core.FluentLoader$ByQuery.list(FluentLoader.java:487) ~[jmix-core-0.3.0-SNAPSHOT.jar:na]
	at io.jmix.securitydata.user.AbstractDatabaseUserRepository.loadUserByUsername(AbstractDatabaseUserRepository.java:141) ~[jmix-security-data-0.3.0-SNAPSHOT.jar:na]
	at org.springframework.security.authentication.dao.DaoAuthenticationProvider.retrieveUser(DaoAuthenticationProvider.java:93) ~[spring-security-core-5.4.2.jar:5.4.2]
	... 100 common frames omitted
Caused by: java.lang.RuntimeException: Error creating UUID from database value '60885987-1b61-4247-94c7-dff348347f93'
	at io.jmix.eclipselink.impl.UuidConverter.convertDataValueToObjectValue(UuidConverter.java:71) ~[jmix-eclipselink-0.3.0-SNAPSHOT.jar:na]
	at org.eclipse.persistence.mappings.foundation.AbstractDirectMapping.getObjectValue(AbstractDirectMapping.java:625) ~[org.eclipse.persistence.core-2.7.7-2-jmix.jar:na]
	at org.eclipse.persistence.mappings.foundation.AbstractDirectMapping.valueFromRow(AbstractDirectMapping.java:1241) ~[org.eclipse.persistence.core-2.7.7-2-jmix.jar:na]
	at org.eclipse.persistence.mappings.foundation.AbstractDirectMapping.buildCloneFromRow(AbstractDirectMapping.java:227) ~[org.eclipse.persistence.core-2.7.7-2-jmix.jar:na]
	at org.eclipse.persistence.internal.descriptors.ObjectBuilder.buildAttributesIntoWorkingCopyClone(ObjectBuilder.java:2007) ~[org.eclipse.persistence.core-2.7.7-2-jmix.jar:na]
	at org.eclipse.persistence.internal.descriptors.ObjectBuilder.buildWorkingCopyCloneFromRow(ObjectBuilder.java:2268) ~[org.eclipse.persistence.core-2.7.7-2-jmix.jar:na]
	at org.eclipse.persistence.internal.descriptors.ObjectBuilder.buildObjectInUnitOfWork(ObjectBuilder.java:858) ~[org.eclipse.persistence.core-2.7.7-2-jmix.jar:na]
	at org.eclipse.persistence.internal.descriptors.ObjectBuilder.buildObject(ObjectBuilder.java:745) ~[org.eclipse.persistence.core-2.7.7-2-jmix.jar:na]
	at org.eclipse.persistence.internal.descriptors.ObjectBuilder.buildObject(ObjectBuilder.java:699) ~[org.eclipse.persistence.core-2.7.7-2-jmix.jar:na]
	at org.eclipse.persistence.queries.ObjectLevelReadQuery.buildObject(ObjectLevelReadQuery.java:858) ~[org.eclipse.persistence.core-2.7.7-2-jmix.jar:na]
	at org.eclipse.persistence.queries.ReadAllQuery.registerResultInUnitOfWork(ReadAllQuery.java:987) ~[org.eclipse.persistence.core-2.7.7-2-jmix.jar:na]
	at org.eclipse.persistence.queries.ReadAllQuery.executeObjectLevelReadQuery(ReadAllQuery.java:598) ~[org.eclipse.persistence.core-2.7.7-2-jmix.jar:na]
	at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeDatabaseQuery(ObjectLevelReadQuery.java:1229) ~[org.eclipse.persistence.core-2.7.7-2-jmix.jar:na]
	at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:911) ~[org.eclipse.persistence.core-2.7.7-2-jmix.jar:na]
	at org.eclipse.persistence.queries.ObjectLevelReadQuery.execute(ObjectLevelReadQuery.java:1188) ~[org.eclipse.persistence.core-2.7.7-2-jmix.jar:na]
	at org.eclipse.persistence.queries.ReadAllQuery.execute(ReadAllQuery.java:485) ~[org.eclipse.persistence.core-2.7.7-2-jmix.jar:na]
	at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeInUnitOfWork(ObjectLevelReadQuery.java:1276) ~[org.eclipse.persistence.core-2.7.7-2-jmix.jar:na]
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.internalExecuteQuery(UnitOfWorkImpl.java:3022) ~[org.eclipse.persistence.core-2.7.7-2-jmix.jar:na]
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1895) ~[org.eclipse.persistence.core-2.7.7-2-jmix.jar:na]
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1877) ~[org.eclipse.persistence.core-2.7.7-2-jmix.jar:na]
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1842) ~[org.eclipse.persistence.core-2.7.7-2-jmix.jar:na]
	at org.eclipse.persistence.internal.jpa.QueryImpl.executeReadQuery(QueryImpl.java:262) ~[org.eclipse.persistence.jpa-2.7.7-2-jmix.jar:na]
	at org.eclipse.persistence.internal.jpa.QueryImpl.getResultList(QueryImpl.java:482) ~[org.eclipse.persistence.jpa-2.7.7-2-jmix.jar:na]
	... 109 common frames omitted
Caused by: java.lang.IllegalArgumentException: 60885987--1b6-1-42-47-9-4c7-dff348347f93
	at io.jmix.core.UuidProvider.fromString(UuidProvider.java:58) ~[jmix-core-0.3.0-SNAPSHOT.jar:na]
	at io.jmix.eclipselink.impl.UuidConverter.convertDataValueToObjectValue(UuidConverter.java:63) ~[jmix-eclipselink-0.3.0-SNAPSHOT.jar:na]
	... 131 common frames omitted
```

**Comment by andreysubbotin** [comment] 2021-02-11 09:46
Duplicate of Haulmont/jmix-core#70

**Closed** 2021-02-16 13:58 UTC
Labels: state: duplicate, type: bug
